name: sample-project
version: '3'
services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    environment:
      DB_host : db
      TZ: Asia/Tokyo
    ports:
      - 3001:3000
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NestDB
    restart: always
    ports:
      - "5439:5432"
    networks:
      - mynetwork

volumes:
  postgres_data:
networks:
  mynetwork: